version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;DataBase=Chinece_Sale_DB;Integrated Security=SSPI;Persist Security Info=False;TrustServerCertificate=True;
      - ConnectionStrings__SeminaryConnection=Server=host.docker.internal;DataBase=Chinese_Sale_32922;Integrated Security=SSPI;Persist Security Info=False;TrustServerCertificate=True;
      - RedisSettings__Host=redis
      - RedisSettings__Port=6379
      - RedisSettings__Password=passforredisdocker
      - RedisSettings__DefaultCacheMinutes=30
    depends_on:
      - redis
    networks:
      - app-network

  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   command: ["redis-server", "--requirepass", "passforredisdocker"]
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - app-network
  redis:
      image: redis:latest
      container_name: architecture-showcase-api-redis-1
      ports:
        - "6379:6379"
      command: ["redis-server", "--requirepass", "passforredisdocker"]
    
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local-cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
    depends_on:
      - kafka

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
